name: Deploy to GCP VM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VM
      run: |
        echo "${{ secrets.VM_SSH_KEY }}" > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "cd /home/${{ secrets.VM_USER }}/ && git pull origin main"
